import Link from "next/link";
import {notFound} from "next/navigation";
import {can} from "@/lib/permissions";
import {requireAnyPermission} from "@/lib/access";
import {submitCisInvoice,reviewCisInvoice} from "./actions";
export default async function Page({params,searchParams}:{params:Promise<{id:string}>,searchParams:Promise<{error?:string;submitted?:string;reviewed?:string}>}){
 const {id}=await params,msg=await searchParams; const {supabase,role}=await requireAnyPermission(["invoices:submit","invoices:review"]);
 const {data:project}=await supabase.from("projects").select("id,reference,title").eq("id",id).single(); if(!project)notFound();
 const {data:rows}=await supabase.from("subcontractor_invoices").select("id,invoice_number,invoice_date,gross_amount,note,invoice_path,status,created_at,profiles:submitted_by(full_name)").eq("project_id",id).order("created_at",{ascending:false});
 const items=await Promise.all((rows||[]).map(async(r:any)=>{const s=await supabase.storage.from("cis-invoices").createSignedUrl(r.invoice_path,900);return{...r,url:s.data?.signedUrl||null}}));
 return <div className="standalone-page"><section className="page-heading"><div><p className="eyebrow">{project.reference}</p><h1>CIS invoices</h1><p>{project.title} · Subcontractor invoice submission and approval</p></div><Link className="secondary-button" href={`/jobs/${id}`}>Back to job</Link></section>
 {msg.error?<div className="notice error-notice">{msg.error}</div>:null}{msg.submitted?<div className="notice success-notice"><strong>Invoice submitted.</strong> It is now waiting for approval.</div>:null}{msg.reviewed?<div className="notice success-notice">Invoice marked {msg.reviewed}.</div>:null}
 {can(role,"invoices:submit")?<section className="panel"><div className="panel-head"><div><p className="eyebrow">CIS crew</p><h2>Upload invoice</h2></div></div><form action={submitCisInvoice} className="form-grid" encType="multipart/form-data"><input type="hidden" name="project_id" value={id}/><label><span>Invoice number</span><input name="invoice_number" required/></label><label><span>Invoice date</span><input name="invoice_date" type="date" required/></label><label><span>Gross invoice (£)</span><input name="gross_amount" type="number" min=".01" step=".01" inputMode="decimal" required/></label><label className="form-span-2"><span>Invoice file</span><input name="invoice" type="file" accept="application/pdf,image/*" capture="environment" required/><small>PDF or clear photograph.</small></label><label className="form-span-2"><span>Note (optional)</span><input name="note"/></label><div className="form-span-2"><button className="primary-button">Submit invoice</button></div></form></section>:null}
 <section className="panel"><div className="panel-head"><div><p className="eyebrow">Status</p><h2>{can(role,"invoices:review")?"Submitted invoices":"My invoices"}</h2></div></div>{items.length?<div className="expense-list">{items.map((r:any)=><article className="expense-card" key={r.id}><div><span>Invoice {r.invoice_number} · {r.invoice_date}</span><strong>£{Number(r.gross_amount).toFixed(2)}</strong><small>{r.profiles?.full_name||"Subcontractor"}{r.note?` · ${r.note}`:""}</small></div><div className="expense-actions"><b className="status-badge">{r.status}</b>{r.url?<a className="text-button" href={r.url} target="_blank" rel="noreferrer">View invoice</a>:null}</div>{can(role,"invoices:review")&&r.status!=="paid"?<form action={reviewCisInvoice} className="expense-review"><input type="hidden" name="project_id" value={id}/><input type="hidden" name="invoice_id" value={r.id}/><input name="review_note" placeholder="Review note (optional)"/><button className="secondary-button" name="status" value="approved">Approve</button><button className="secondary-button" name="status" value="rejected">Reject</button>{r.status==="approved"?<button className="primary-button" name="status" value="paid">Mark paid</button>:null}</form>:null}</article>)}</div>:<div className="empty-state compact-empty"><strong>No invoices submitted.</strong></div>}</section></div>
}