import Link from "next/link";
import {notFound} from "next/navigation";
import {can} from "@/lib/permissions";
import {requireAnyPermission} from "@/lib/access";
import {submitDaywork,acknowledgeDaywork} from "./actions";
export default async function Dayworks({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{error?:string}>}){
 const {id}=await params;const {error}=await searchParams;const {supabase,role}=await requireAnyPermission(["jobs:view_all","jobs:view_assigned"]);
 const [{data:project},{data:rows},{data:vars}]=await Promise.all([supabase.from("projects").select("id,reference,title").eq("id",id).single(),supabase.from("daywork_sheets").select("*").eq("project_id",id).order("work_date",{ascending:false}),supabase.from("variations").select("id,reference,title").eq("project_id",id)]);if(!project)notFound();
 return <div className="standalone-page"><section className="page-heading"><div><p className="eyebrow">{project.reference} · site record</p><h1>Daywork sheets</h1><p>Record labour, plant and materials daily. Client acknowledgement confirms the resources/work recorded, not the final valuation.</p></div><Link className="secondary-button" href={"/jobs/"+id}>Job</Link></section>{error?<p className="form-error page-error">{error}</p>:null}
 {can(role,"variations:raise")?<section className="panel"><div className="panel-head"><div><p className="eyebrow">Daily record</p><h2>New daywork sheet</h2></div></div><form action={submitDaywork} className="compact-form"><input type="hidden" name="project_id" value={id}/><div className="form-grid"><label className="field"><span>Date</span><input type="date" name="work_date" required/></label><label className="field"><span>Related variation</span><select name="variation_id"><option value="">Not linked yet</option>{(vars||[]).map(v=><option key={v.id} value={v.id}>{v.reference} · {v.title}</option>)}</select></label><label className="field"><span>Instruction by</span><input name="instruction_by_name"/></label><label className="field"><span>Company</span><input name="instruction_by_company"/></label></div><label className="field"><span>Work undertaken *</span><textarea name="work_description" rows={3} required/></label><div className="form-grid"><label className="field"><span>Labour / operative</span><input name="labour_description"/></label><label className="field"><span>Total labour hours</span><input name="labour_hours" type="number" step=".5"/></label><label className="field"><span>Plant</span><input name="plant_description"/></label><label className="field"><span>Plant hours</span><input name="plant_hours" type="number" step=".5"/></label></div><label className="field"><span>Materials used</span><textarea name="materials" rows={2}/></label><label className="field"><span>Photo / evidence notes</span><textarea name="evidence_notes" rows={2}/></label><button className="primary-button" type="submit">Submit today's daywork</button></form></section>:null}
 <section className="panel"><div className="panel-head"><div><p className="eyebrow">Register</p><h2>Dayworks</h2></div></div>{rows?.length?<div className="stack-list">{rows.map(d=><article className="variation-card" key={d.id}><div className="variation-head"><span><strong>{d.reference} · {d.work_date}</strong><small>{d.work_description}</small></span><span className="status-badge">{d.status}</span></div><p>{d.instruction_by_name ? "Instruction: "+d.instruction_by_name+(d.instruction_by_company?" · "+d.instruction_by_company:"") : "Instruction source not recorded"}</p>{can(role,"commercial:edit")&&d.status==="submitted"?<form action={acknowledgeDaywork} className="compact-form"><input type="hidden" name="project_id" value={id}/><input type="hidden" name="daywork_id" value={d.id}/><div className="form-grid"><label className="field"><span>Client/site representative *</span><input name="client_name" required/></label><label className="field"><span>Position</span><input name="client_position"/></label><label className="field"><span>Company</span><input name="client_company"/></label><label className="field"><span>Email</span><input name="client_email" type="email"/></label></div><label className="field"><span>Acknowledgement note</span><textarea name="client_acknowledgement_note" rows={2}/></label><p><small>I confirm the labour, plant, materials and work recorded above were undertaken/supplied on this date. This acknowledgement does not alter the contractual basis on which the work will be valued.</small></p><div className="inline-actions"><button className="primary-button" name="decision" value="acknowledged">Record acknowledgement</button><button className="secondary-button" name="decision" value="disputed">Record dispute</button></div></form>:null}</article>)}</div>:<div className="empty-state compact-empty"><strong>No daywork sheets.</strong><p>Submit them on the day the work is carried out.</p></div>}</section></div>
}