import Link from "next/link";
import { notFound } from "next/navigation";
import { can } from "@/lib/permissions";
import { requireAnyPermission } from "@/lib/access";
import { submitSiteIssue, resolveSiteIssue } from "./actions";

export default async function IssuesPage({params,searchParams}:{params:Promise<{id:string}>,searchParams:Promise<{error?:string;saved?:string}>}) {
 const {id}=await params; const msg=await searchParams; const {supabase,role}=await requireAnyPermission(["issues:submit","issues:review"]);
 const {data:project}=await supabase.from("projects").select("id,reference,title").eq("id",id).single(); if(!project) notFound();
 const {data:rows}=await supabase.from("site_issues").select("id,category,detail,photo_path,status,created_at,profiles:raised_by(full_name)").eq("project_id",id).order("created_at",{ascending:false});
 const enriched=await Promise.all((rows||[]).map(async row=>{if(!row.photo_path)return {...row,photoUrl:null};const s=await supabase.storage.from("site-issues").createSignedUrl(row.photo_path,900);return {...row,photoUrl:s.data?.signedUrl||null};}));
 return <div className="standalone-page"><section className="page-heading"><div><p className="eyebrow">{project.reference}</p><h1>Report an issue</h1><p>{project.title} · Record site problems when they happen</p></div><Link className="secondary-button" href={`/jobs/${id}`}>Back to job</Link></section>
 {msg.error?<div className="notice error-notice">{msg.error}</div>:null}{msg.saved?<div className="notice success-notice">Issue recorded.</div>:null}
 {can(role,"issues:submit")?<section className="panel"><form action={submitSiteIssue} className="form-grid" encType="multipart/form-data"><input type="hidden" name="project_id" value={id}/><label><span>Problem</span><select name="category" required defaultValue=""><option value="" disabled>Select problem</option><option value="substrate">Substrate</option><option value="moisture">Moisture</option><option value="damage">Damage</option><option value="materials">Materials</option><option value="access">Access</option><option value="safety">Safety</option><option value="other">Other</option></select></label><label className="form-span-2"><span>What happened?</span><textarea name="detail" rows={4} required placeholder="Short factual description"/></label><label className="form-span-2"><span>Photo (recommended)</span><input name="photo" type="file" accept="image/*" capture="environment"/></label><div className="form-span-2"><button className="primary-button" type="submit">Report issue</button></div></form></section>:null}
 <section className="panel"><div className="panel-head"><div><p className="eyebrow">Site record</p><h2>Reported issues</h2></div></div>{enriched.length?<div className="expense-list">{enriched.map((row:any)=><article className="expense-card" key={row.id}><div><span>{new Date(row.created_at).toLocaleString("en-GB")} · {row.category}</span><strong>{row.detail}</strong><small>{row.profiles?.full_name||"Worker"}</small></div><div className="expense-actions"><b className="status-badge">{row.status}</b>{row.photoUrl?<a className="text-button" href={row.photoUrl} target="_blank" rel="noreferrer">View photo</a>:null}</div>{can(role,"issues:review")&&row.status!=="resolved"?<form action={resolveSiteIssue} className="expense-review"><input type="hidden" name="project_id" value={id}/><input type="hidden" name="issue_id" value={row.id}/><input name="resolution_note" placeholder="Resolution note"/><button className="primary-button">Resolve</button></form>:null}</article>)}</div>:<div className="empty-state compact-empty"><strong>No site issues recorded.</strong></div>}</section></div>;
}